In [2]:
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [3]:
r = 0.05
delta_T = 1/360

### Портфель 1

In [4]:
portfolio = [
    {
        'type': 'future', # фьючерс
        'underlying': 'stock1', # тикер базового актива
        'ds': True, # ежедневная переоценка

        'quantity': 2000, # кол-во
        'daily_limit': 500, # дневной лимит
        'execution_lag': 1, # на какой день от дефолта начать ликвидацию
        'days_to_maturity': 61, # дней до исполнения
    },
    {
        'type': 'call_future', # колл на фьючерс
        'underlying': 'stock1',
        'ds': True,

        'quantity': -2000,
        'daily_limit': 10000,
        'execution_lag': 10,
        'days_to_maturity': 71, # дней до исполнения
        'strike': 95 # цена исполнения

    },
    {
        'type': 'put_future', # пут на фьючерс
        'underlying': 'stock1',
        'ds': True,

        'quantity': 2000,
        'daily_limit': 10000,
        'execution_lag': 10,
        'days_to_maturity': 71, # дней до исполнения
        'strike': 95 # цена исполнения
    }
]

In [5]:
# подхватываем базовые активы (тикеры в идеале)
underlyings = list(set([asset['underlying'] for asset in portfolio]))
underlyings

['stock1']

In [6]:
# подхватываем для них drift, volatility, covamatrix (corr matrix)
# в том же порядке
mu = np.array([0.1])
sigma = np.array([0.3])
spot = np.array([100])

In [7]:
# определяем период ликвидации и число симуляций
T = 10
N = 20000

### портфель 2

In [8]:
portfolio = [
    {
        'type': 'call_stock',  # колл на акцию 1
        'underlying': 'stock1',  # тикер базового актива
        'ds': True,  # ежедневная переоценка

        'quantity': 1000,  # кол-во
        'daily_limit': 10000,  # дневной лимит
        'execution_lag': 10,  # на какой день от дефолта начать ликвидацию
        'days_to_maturity': 61,  # дней до исполнения
        'strike': 110  # цена исполнения
    },
    {
        'type': 'call_stock',  # колл на акцию
        'underlying': 'stock2',
        'ds': True,

        'quantity': 1000,
        'daily_limit': 500,
        'execution_lag': 1,
        'days_to_maturity': 61,  # дней до исполнения
        'strike': 120  # цена исполнения: только для фьючерсов и опционов
    }
]

In [9]:
# подхватываем базовые активы (тикеры в идеале)
underlyings = list(set([asset['underlying'] for asset in portfolio]))
underlyings

['stock2', 'stock1']

In [10]:
# подхватываем для них drift, volatility, covamatrix (corr matrix)
# в том же порядке
mu = np.array([0.05, 0.1])
sigma = np.array([0.25, 0.4])
spot = np.array([100, 120])

corr = np.array([[sigma[0]**2, 0.5* sigma[0]*sigma[1]],
                 [0.5*sigma[0]*sigma[1], sigma[1]**2]])

In [11]:
# определяем период ликвидации и число симуляций
T = 10
N = 20000

### портфель 3

In [12]:
portfolio = [
    {
        'type': 'future', # фьючерс
        'underlying': 'stock1', # тикер базового актива
        'ds': True, # ежедневная переоценка

        'quantity': 1000, # кол-во
        'daily_limit': 250, # дневной лимит
        'execution_lag': 1, # на какой день от дефолта начать ликвидацию
        'days_to_maturity': 61, # дней до исполнения
    },
    {
        'type': 'call_future', # колл на фьючерс
        'underlying': 'stock1',
        'ds': True,

        'quantity': 1000,
        'daily_limit': 250,
        'execution_lag': 1,
        'days_to_maturity': 61, # дней до исполнения
        'strike': 110 # цена исполнения

    },
    {
        'type': 'put_future', # пут на фьючерс
        'underlying': 'stock1',
        'ds': True,

        'quantity': 1000,
        'daily_limit': 250,
        'execution_lag': 1,
        'days_to_maturity': 61, # дней до исполнения
        'strike': 110 # цена исполнения
    },
    {
        'type': 'call_future', # колл на фьючерс
        'underlying': 'stock1',
        'ds': True,

        'quantity': 1000,
        'daily_limit': 250,
        'execution_lag': 5,
        'days_to_maturity': 160, # дней до исполнения
        'strike': 110 # цена исполнения

    },
    {
        'type': 'put_future', # пут на фьючерс
        'underlying': 'stock1',
        'ds': True,

        'quantity': 1000,
        'daily_limit': 250,
        'execution_lag': 5,
        'days_to_maturity': 160, # дней до исполнения
        'strike': 110 # цена исполнения
    },
    {
        'type': 'call_future', # колл на фьючерс
        'underlying': 'stock1',
        'ds': True,

        'quantity': -1000,
        'daily_limit': 10000,
        'execution_lag': 10,
        'days_to_maturity': 360, # дней до исполнения
        'strike': 110 # цена исполнения

    },
    {
        'type': 'put_future', # пут на фьючерс
        'underlying': 'stock1',
        'ds': True,

        'quantity': -1000,
        'daily_limit': 10000,
        'execution_lag': 10,
        'days_to_maturity': 360, # дней до исполнения
        'strike': 110 # цена исполнения
    }
]

In [13]:
# подхватываем базовые активы (тикеры в идеале)
underlyings = list(set([asset['underlying'] for asset in portfolio]))
underlyings

['stock1']

In [14]:
# подхватываем для них drift, volatility, covamatrix (corr matrix)
# в том же порядке
mu = np.array([0.1])
sigma = np.array([0.3])
spot = np.array([100])

In [15]:
# определяем период ликвидации и число симуляций
T = 10
N = 20000

### симуляция

In [16]:
def gbm_simulate_path(seed, S0, mu, sigma, T, N, cov=None):
    np.random.seed()
    dim = np.size(S0)
    
    t = np.arange(0, T+1)*delta_T
    S = np.zeros([dim, len(t)])
    S[:, 0] = S0
    
    if cov is not None:
        A = np.linalg.cholesky(cov)     
    
    for j in range(1, len(t)):
        drift = (mu - sigma**2/2) * (t[j] - t[j-1])
        Z = np.random.normal(0.0, 1.0, dim)
        
        if cov is not None:
            mat = np.matmul(A, Z)
        else:
            mat = Z
            
        diffusion = mat * np.sqrt(t[j] - t[j-1])
        
        S[:, j] = S[:, j-1] * np.exp(drift + diffusion)
        
    return S, t



In [17]:
from core_methodology import future_price, forward_contract_value
from core_methodology import option_stock, option_future

In [18]:
SS = np.zeros([N, len(spot), T + 1])

for k in range(N):
    seed = int(np.random.uniform(1, 2**32 - 1, 1))
    SS[k, :, :] = gbm_simulate_path(seed, spot, mu, sigma, T, N)[0]

In [19]:
t = 360 * delta_T - np.arange(0, T+1) * delta_T

print(SS[:,0,:])

[[100.          94.86240094  89.33326635 ... 113.97477964 117.80703259
  117.78177869]
 [100.          94.58145676  94.00785405 ...  90.46026865  88.12650043
   90.12928046]
 [100.          88.74206311  89.58690869 ...  92.83579074  93.29209535
   89.70921615]
 ...
 [100.          95.14386761  86.83250448 ...  83.92533579  86.72170911
   89.75274965]
 [100.          96.0012459   95.95394214 ... 111.24377798 114.97475406
  114.32392554]
 [100.          90.32356488  95.06815412 ...  94.55705437 102.028707
   97.74282749]]


In [20]:
# теперь нужно создать price_paths
price_paths = np.zeros(shape=(N, len(portfolio), T + 1))

for i in range(len(portfolio)):
    for j in range(len(underlyings)):
        if portfolio[i]['underlying'] == underlyings[j]:
            
            if portfolio[i]['type'] == 'stock':
                price_paths[:, i, :] = SS[:, j, :]
                
            elif portfolio[i]['type'] == 'forward':
                t = portfolio[i]['days_to_maturity']*delta_T \
                    - np.arange(0, T+1)*delta_T

                S0 = SS[:, j, :]
                F0 = future_price(S0, r, 0, t)

                price_paths[:, i, :] = forward_contract_value(F0, portfolio[i]['strike'], r, t)

            elif portfolio[i]['type'] == 'future':
                t = portfolio[i]['days_to_maturity']*delta_T \
                    - np.arange(0, T+1)*delta_T

                S0 = SS[:, j, :]

                price_paths[:, i, :] = future_price(S0, r, 0, t)
            
            elif portfolio[i]['type'] == 'call_stock':
                t = portfolio[i]['days_to_maturity']*delta_T \
                    - np.arange(0, T+1)*delta_T

                S0 = SS[:, j, :]

                price_paths[:, i, :] = option_stock(S0, portfolio[i]['strike'], r, sigma[j], t, param='call')
            
            elif portfolio[i]['type'] == 'put_stock':
                t = portfolio[i]['days_to_maturity']*delta_T \
                    - np.arange(0, T+1)*delta_T

                S0 = SS[:, j, :]

                price_paths[:, i, :] = option_stock(S0, portfolio[i]['strike'], r, sigma[j], t, param='put')
            
            elif portfolio[i]['type'] == 'call_future':
                t = portfolio[i]['days_to_maturity']*delta_T - np.arange(0, T+1)*delta_T

                S0 = SS[:, j, :]
                F0 = future_price(S0, r, 0, t)

                price_paths[:, i, :] = option_future(F0, portfolio[i]['strike'], r, sigma[j], t, param='call')

            
            elif portfolio[i]['type'] == 'put_future':
                t = portfolio[i]['days_to_maturity']*delta_T - np.arange(0, T+1)*delta_T

                S0 = SS[:, j, :]
                F0 = future_price(S0, r, 0, t)

                price_paths[:, i, :] = option_future(F0, portfolio[i]['strike'], r, sigma[j], t, param='put')
                


In [21]:
price_paths

array([[[1.00850821e+02, 9.56562239e+01, 9.00683104e+01, ...,
         1.14816856e+02, 1.18660941e+02, 1.18619028e+02],
        [1.83080698e+00, 7.87198432e-01, 2.49448640e-01, ...,
         7.86254062e+00, 1.05575744e+01, 1.04873336e+01],
        [1.09027992e+01, 1.50119397e+01, 2.00184765e+01, ...,
         3.08101169e+00, 1.95895926e+00, 1.92914126e+00],
        ...,
        [1.26026892e+01, 1.59513870e+01, 2.01024804e+01, ...,
         5.82882196e+00, 4.58871241e+00, 4.57543358e+00],
        [1.00200776e+01, 7.61138241e+00, 5.43206472e+00, ...,
         1.80210210e+01, 2.06296440e+01, 2.05859807e+01],
        [1.46553143e+01, 1.73987518e+01, 2.07631044e+01, ...,
         8.79780399e+00, 7.58872391e+00, 7.58486643e+00]],

       [[1.00850821e+02, 9.53729288e+01, 9.47813611e+01, ...,
         9.11286136e+01, 8.87652735e+01, 9.07699626e+01],
        [1.83080698e+00, 7.48570095e-01, 6.53111129e-01, ...,
         2.44383768e-01, 1.29669255e-01, 2.03779363e-01],
        [1.09027992e+01, 

In [22]:
from core_methodology import CORE

In [23]:
core = CORE(portfolio, price_paths)
core.__dict__

{'_portfolio': [{'type': 'future',
   'underlying': 'stock1',
   'ds': True,
   'quantity': 1000,
   'daily_limit': 250,
   'execution_lag': 1,
   'days_to_maturity': 61},
  {'type': 'call_future',
   'underlying': 'stock1',
   'ds': True,
   'quantity': 1000,
   'daily_limit': 250,
   'execution_lag': 1,
   'days_to_maturity': 61,
   'strike': 110},
  {'type': 'put_future',
   'underlying': 'stock1',
   'ds': True,
   'quantity': 1000,
   'daily_limit': 250,
   'execution_lag': 1,
   'days_to_maturity': 61,
   'strike': 110},
  {'type': 'call_future',
   'underlying': 'stock1',
   'ds': True,
   'quantity': 1000,
   'daily_limit': 250,
   'execution_lag': 5,
   'days_to_maturity': 160,
   'strike': 110},
  {'type': 'put_future',
   'underlying': 'stock1',
   'ds': True,
   'quantity': 1000,
   'daily_limit': 250,
   'execution_lag': 5,
   'days_to_maturity': 160,
   'strike': 110},
  {'type': 'call_future',
   'underlying': 'stock1',
   'ds': True,
   'quantity': -1000,
   'daily_limi

In [24]:
%%time
opt_strategy = core.optimized_strategy()

Set parameter Username
Academic license - for non-commercial use only - expires 2022-08-03
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (mac64[arm])
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 200103 rows, 71 columns and 12800166 nonzeros
Model fingerprint: 0x4d51d7c3
Variable types: 1 continuous, 70 integer (0 binary)
Coefficient statistics:
  Matrix range     [7e-12, 2e+02]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+03, 1e+03]
  RHS range        [7e-02, 3e+05]
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.
Found heuristic solution: objective -23990.60175
Presolve removed 6985 rows and 28 columns
Presolve time: 4.69s
Presolved: 193118 rows, 43 columns, 7338317 nonzeros
Variable types: 1 continuous, 42 integer (0 binary)

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0      handle free variables                 

In [29]:
print(opt_strategy)
print(core.get_c_value())
i = core.get_argmin_scenario()
core.get_pl_matrix()[i].sum(axis=0)

[[  52    0   94  130   63    0   64  250  250   97]
 [  84    0  159    7    0    0    0  250  250  250]
 [   7   32  143   68    0    0    0  250  250  250]
 [   0    0    0    0  250    0    0  250  250  250]
 [   0    0    0    0  243    7    0  250  250  250]
 [   0    0    0    0    0    0    0    0    0 1000]
 [   0    0    0    0    0    0    0    0    0 1000]]
2671.447978971887


array([ -910.53408199,   254.38122535,   -24.07363107,  -282.65213495,
         -29.00030364,   -54.77574167,    36.73052344,  -175.46369042,
         -25.21237586, -1460.84776816])

In [30]:
print(core.naive_strategy())
print(core.get_c_value())
i = core.get_argmin_scenario()
core.get_pl_matrix()[i].sum(axis=0)

[[ 250  250  250  250    0    0    0    0    0    0]
 [ 250  250  250  250    0    0    0    0    0    0]
 [ 250  250  250  250    0    0    0    0    0    0]
 [   0    0    0    0  250  250  250  250    0    0]
 [   0    0    0    0  250  250  250  250    0    0]
 [   0    0    0    0    0    0    0    0    0 1000]
 [   0    0    0    0    0    0    0    0    0 1000]]
36074.848533536635


array([  2674.36441578,  -1194.49544872,   -105.81864016,   -704.13176179,
        -1412.71967527,   -679.03744185,  -1608.26238371,  -4400.89306948,
        -7167.16900845, -21476.68551989])

### жругой случай

In [ ]:
def gdm_simulate(seed, S0, mu, sigma, cov, T, N):
    np.random.seed(seed)
    dim = np.size(S0)
    
    t = np.linspace(0, T, N)
    A = np.linalg.cholesky(cov)
    S = np.zeros([dim, int(N)])
    S[:, 0] = S0
    
    for i in range(1, N):
        drift = (mu - sigma**2 / 2) * (t[i] - t[i - 1])
        W = np.random.normal(0.0, 1.0, dim)
        diffusion = np.matmul(A, W) * np.sqrt(t[i] - t[i - 1])
        
        S[:, i] = S[:, i - 1] * np.exp(drift + diffusion)
        
    return S, t

In [ ]:
intc = pd.read_csv('INTC.csv')
amd = pd.read_csv('AMD.csv')

intc.info()

In [ ]:
seed = 22

dim = 2
T = 1
N = 2**9

S0 = np.array([100, 100])

In [ ]:
# log returns
intc['log_returns'] = np.log(intc['Adj Close']).diff()
amd['log_returns'] = np.log(amd['Adj Close']).diff()

In [ ]:
plt.figure(figsize=(16,8))
plt.title('Log Returns History')
plt.plot(intc['log_returns'], label='INTC')
plt.plot(amd['log_returns'], label='AMD')
plt.legend()
plt.show()

In [ ]:
# expected returns
mean_intc = intc['log_returns'][1:].mean()
mean_amd = amd['log_returns'][1:].mean()

mu = np.array([mean_intc, mean_amd])
mu

In [ ]:
# volatility
std_intc = intc['log_returns'][1:].std()
std_amd = amd['log_returns'][1:].std()

sigma = np.array([std_intc, std_amd])
sigma

In [ ]:
# covariance matrix
cov = np.cov(intc['log_returns'][1:], amd['log_returns'][1:])
cov

In [ ]:
stocks, time = gdm_simulate(seed, S0, mu, sigma, cov, T, N)